x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

volumes:
  postgres:

services:

  postgres:
    environment:
    - POSTGRES_DB=keycloak
    - POSTGRES_USER=keycloak
    - POSTGRES_PASSWORD=password
    image: postgres:16
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
    - postgres:/var/lib/postgresql
    logging: *logging

  openldap:
    image: bitnami/openldap:2.6
    environment:
      LDAP_PORT_NUMBER: 389
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    command: --verbose start-dev --features=preview --import-realm
    depends_on:
    - postgres 
    - openldap
    environment:
    - KC_BOOTSTRAP_ADMIN_USERNAME=keycloak
    - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    - KC_LOG_LEVEL=INFO,org.keycloak:info
    - KC_DB=postgres
    - KC_DB_URL_HOST=postgres
    - KC_DB_URL_PORT=5432
    - KC_DB_URL_DATABASE=keycloak
    - KC_DB_USERNAME=keycloak
    - KC_DB_PASSWORD=password
    - KC_LOG_CONSOLE_COLOR=true
    - KC_FEATURES=preview
    - JAVA_OPTS_APPEND=-XX:UseSVE=0
    - QUARKUS_HTTP_ACCESS_LOG_ENABLED=true
    - QUARKUS_HTTP_RECORD_REQUEST_START_TIME=true
# Enable for remote java debugging
#    - DEBUG=true
#    - DEBUG_PORT=*:8787
    ports:
    - "8080:8080"
# Enable for remote java debugging
#    - "8787:8787"
    volumes:
# Make the custom-user-federation-example extension available to Keycloak. The :z option is required and tells Docker that the volume content will be shared between containers.
#    - ./custom-user-federation-example/build/libs/custom-user-federation-example-all.jar:/opt/keycloak/providers/custom-user-federation-example-all.jar:z
#    - ./provider/misc:/opt/keycloak/misc:z
     - ./config/realm.json:/opt/keycloak/data/import/realm.json:ro
